extends: "spectral:oas"
rules:
  contact-properties: true
  tag-description: true
  oas3-parameter-description: true
  oas3-unused-component: true
  operation-id-kebab-case:
    given: "$..operationId"
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9\-]*$