openapi.yaml:
  no-required-schema-properties-undefined:
    - '#/components/schemas/dimension_spatial_horizontal/allOf/1/required/0'
    - '#/components/schemas/dimension_spatial_vertical/allOf/1/anyOf/0/required/0'
    - '#/components/schemas/dimension_spatial_vertical/allOf/1/anyOf/1/required/0'
    - '#/paths/~1jobs~1{job_id}~1estimate/get/responses/200/content/application~1json/schema/anyOf/0/required/0'
    - '#/paths/~1jobs~1{job_id}~1estimate/get/responses/200/content/application~1json/schema/anyOf/1/required/0'
    - '#/paths/~1jobs~1{job_id}~1estimate/get/responses/200/content/application~1json/schema/anyOf/2/required/0'
