extends:
  - recommended

openapi:
  expandResponses: "200,201,202,203,204"
  pathInMiddlePanel: true

apis:
  core:
    root: ./openapi.yaml
  commercial-data:
    root: ./extensions/commercial-data/openapi.yaml
  processing-parameters:
    root: ./extensions/processing-parameters/openapi.yaml
  workspaces:
    root: ./extensions/workspaces/openapi.yaml