extends: "spectral:oas"
# don't error on circular schemas, these are currently not supported by spectral
# https://github.com/stoplightio/spectral/issues/894
except:
  "openapi.yaml#/components/schemas/process_graph/example":
    - oas3-valid-schema-example
  "openapi.yaml#/paths/~1processes/get/responses/200/content/application~1json/example":
    - oas3-valid-oas-content-example
  "openapi.yaml#/paths/~1processes~1{namespace}/get/responses/200/content/application~1json/example":
    - oas3-valid-oas-content-example
  "openapi.yaml#/paths/~1service_types/get/responses/200/content/application~1json/example":
    - oas3-valid-oas-content-example
  "openapi.yaml#/paths/~1file_formats/get/responses/200/content/application~1json/example":
    - oas3-valid-oas-content-example
rules:
  # Ported from Spectral 4.0
  contact-properties: true
  tag-description: true
  oas3-parameter-description: true
  operation-2xx-response: off # remove this line once /process_graphs/... endpoints have been removed
  oas3-unused-components-schema: false # Broken: https://github.com/stoplightio/spectral/issues/1271
  operation-summary-formatted:
    description: Operation `summary` should start with upper case and not end with a dot.
    recommended: true
    type: style
    given: '$.paths.*[?( @property === ''get'' || @property === ''put'' || @property === ''post'' || @property === ''delete'' || @property === ''options'' || @property === ''head'' || @property === ''patch'' || @property === ''trace'' )]'
    then:
      field: summary
      function: pattern
      functionOptions:
        match: '^[A-Z].*[^\.]$'
    tags:
      - operation
  operation-id-kebab-case:
    given: "$"
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9\-]*$