extends: "spectral:oas"
rules:
  # https://github.com/stoplightio/spectral/issues/892
  # Remove whenever fixed in spectral
  oas3-operation-security-defined: false
  # https://github.com/stoplightio/spectral/issues/883
  # Remove whenever fixed in spectral
  example-value-or-externalValue:
    description: Example should have either a `value` or `externalValue` field.
    recommended: true
    type: style
    given: $..examples
    then:
      function: xor
      functionOptions:
        properties:
          - externalValue
          - value
  # https://github.com/stoplightio/spectral/issues/894
  # Remove whenever fixed in spectral
  oas3-valid-schema-example: info
  oas3-valid-content-schema-example: info
  # Ported from Spectral 4.0
  contact-properties: true
  tag-description: true
  oas3-parameter-description: true
  operation-summary-formatted:
    description: Operation `summary` should start with upper case and not end with a dot.
    recommended: true
    type: style
    given: '$.paths.*[?( @property === ''get'' || @property === ''put'' || @property === ''post'' || @property === ''delete'' || @property === ''options'' || @property === ''head'' || @property === ''patch'' || @property === ''trace'' )]'
    then:
      field: summary
      function: pattern
      functionOptions:
        match: '^[A-Z].*[^\.]$'
    tags:
      - operation
  operation-id-kebab-case:
    given: "$"
    then:
      function: pattern
      functionOptions:  # this object be passed down as options to the custom function
        match: ^[a-z][a-z0-9\-]*$