name: Test API Spec
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - name: Run core tests
        run: |
          npm install
          npm test
      - name: Run commercial-data tests
        run: |
          cd extensions/commercial-data
          npm install
          npm test