name: Test API Spec
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm install
          npm test