name: Test API Spec
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v5
      - run: npm install
      - run: npm test